version: '2'

services:

  hadoop-master:
    image: dataday/hadoop-master
    ports:
      - 8088:8088
      - 50070:50070


  # Copy local data to hdfs
  data2hdfs:
    image: dataday/hadoop-client
    volumes:
      - ./data:/app/data
    command: bash -c 'hadoop fs -mkdir -p /app/data && hadoop fs -put -f /app/data/* /app/data'
    depends_on:
      - hadoop-master


  # Interactive client terminal
  client:
    image: dataday/hadoop-client
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    command: /bin/bash
    tty: true
    depends_on:
      - hadoop-master


  # Wordcount using MapReduce Java API
  wc-mapred:
    image: dataday/cc-examples
    #command: 'wc s3a://commoncrawl/crawl-data/CC-MAIN-2013-48/segments/1386163035819/wet/CC-MAIN-20131204131715-00000-ip-10-33-133-15.ec2.internal.warc.wet.gz /app/data/wordcount'
    #command: 'wc s3a://commoncrawl/crawl-data/CC-MAIN-2013-48/segments/1386163035819/wet/*.warc.wet.gz /app/data/wordcount'
    command: 'wc /app/data/*.warc.wet.gz /app/data/wordcount'
    depends_on:
      - hadoop-master


  # PageRank using Pig
  pagerank-pig:
    build: ./01-pagerank
    environment:
      - INPUT=/app/data/*.warc.wat.gz
      - OUTPUT=/app/pagerank
      - DAMPING_FACTOR=0.5
      - ITER_NUM=10
    depends_on:
      - hadoop-master
