version: '2'

services:

  hadoop-master:
    image: sequenceiq/hadoop-docker:2.7.0
    ports:
      - 8088:8088
      - 50070:50070
      - 50075:50075

  ccwordcount:
    image: dataday/cc-examples
    volumes:
      - ../data:/app/data
    command: ./run-example.sh wc
    depends_on:
      - hadoop-master

  ccservertype:
    image: dataday/cc-examples
    volumes:
      - ../data:/app/data
    command: ./run-example.sh st
    depends_on:
      - hadoop-master
