version: '2'

services:

  hadoop-master:
    image: dataday/hadoop-master
    ports:
      - 8088:8088
      - 50070:50070
      - 50075:50075
      - 10020:10020

  ccwordcount:
    image: dataday/cc-examples
    volumes:
      - ../data:/app/data
    command: ./run-example.sh wc
    depends_on:
      - hadoop-master

  ccservertype:
    image: dataday/cc-examples
    volumes:
      - ../data:/app/data
    command: ./run-example.sh st
    depends_on:
      - hadoop-master

  pig:
    image: dataday/hadoop-client
    volumes:
      - ../data:/app/data
    command: /bin/bash
    tty: true
    depends_on:
      - hadoop-master
